#!/usr/bin/php
<?php
//
// Sept 8 2014 - whooper
//
// generate JSON string with SP30 data

// define curl headers
$headers= array('Content-Type: application/json'); 

// read monitor.php
// please note file location as per the repo
// and the use of output buffers.

ob_start();
include("../../var/www/historian.php");
$json = ob_get_clean();

//
// proceed only if the JSON file is returned
// 

if(strlen($json)>0) {
	// curl post
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL,"http://your.historian.location");
	curl_setopt($ch, CURLOPT_POST, true);
	curl_setopt($ch, CURLOPT_HEADER, false);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	$server_output = curl_exec ($ch);
	curl_close ($ch);

  //
	// The remote script should OK the transfer
	// show output	
	
	if ($server_output == "OK") {
 		echo "\n>> Post OK \n\n";
	} else { 
 		echo "\n>> Post Failed: ".$server_output."\n\n"; 
	}

	// echo "\n>> Payload: \n".$json."\n\n"; 
} else {
  echo "Can't get JSON string from monitor.php ..";
}
?>
